#!/usr/bin/bash

# while true
# do
#     scene=$(ls -d ~/.local/src/paperview/wallpaper/*/ | shuf -n 1)
#     timeout 600 paperview $scene 5 # See Multi-Monitor Use above for multiple monitor support
# done

#!/bin/bash

# get the list of the proccess id
for pid in $(pidof -x curseanimwall); do 
    if [ $pid != $$ ]; then
        kill -3 $pid
        exit 1
    fi
done

cd "$HOME/.local/src/paperview/wallpaper"

wallpaper=($(ls))

for pic in "${wallpaper[@]}"
    do 
    :
    wallpath+=($(readlink -f $pic)) 
done

while true; do
    for p in "${wallpath[@]}"
        do 
        :
        paperview $p 10
        sleep 10s
    done
done

