#!/bin/bash
while true; do
  # to have the status at the bottom center bar
  xsetroot -name "dwm-6.2;$(date | sed s/,//) .. FILE $(df -h / | sed '2!d' | awk '{print $4}') remaining  RAM .. $(free -h | sed '2!d' | awk '{print $4}') remaining .. CPU $(acpi -t | awk '{print $4}')C .. $(acpi | sed '1!d')"
  # xsetroot -name " $(date | sed s/,//)    $(df -h / | sed '2!d' | awk '{print $4}') remaining   $(free -h | sed '2!d' | awk '{print $4}') remaining   $(acpi -t | awk '{print $4}')C    $(acpi | sed '1!d')"
sleep 1;
done

